### 1. Create an NumPy Array using List

In [4]:
L1 = np.array([10,20,30]) # Create ndarray

print("ndarray created using list elements:-",L1)

ndarray created using list elements:- [10 20 30]


### 2. Create a Multi-Dimensional Array

In [8]:
MD = np.array([[10,20,30],[40,50,60]]) 

print ("Creating Multi-Dimensional Array:-\n\n", MD)

Creating Multi-Dimensional Array:-

 [[10 20 30]
 [40 50 60]]


### 3. Represent The Minimum Dimensions

In [26]:
# Use ndmin funtion to specify how many minimum dimensions you wanted to create an array with. 

# Minimum dimension

Dim = np.array([10, 20, 30,40], ndmin = 2) 

print("Creation of minimum dimensions of the array:-", Dim)

print()

Dim1 = np.array([10, 20, 30,40], ndmin = 3) 

print("Creation of minimum dimensions of the array:-", Dim1)

print()

Dim2 = np.array([[11,22,33], [45, 90, 6]], ndmin = 2) 

print("Creation of minimum dimensions of the array:-\n\n", Dim2)

print()

Dim3 = np.array([[121,222,333], [455, 900, 600]], ndmin = 3) 

print("Creation of minimum dimensions of the array:-\n\n", Dim3)

Creation of minimum dimensions of the array:- [[10 20 30 40]]

Creation of minimum dimensions of the array:- [[[10 20 30 40]]]

Creation of minimum dimensions of the array:-

 [[11 22 33]
 [45 90  6]]

Creation of minimum dimensions of the array:-

 [[[121 222 333]
  [455 900 600]]]


### 4. Change The Data Type

In [33]:
# We can also specify the type of the array elements using dtype param. 

# We need to specify the name of the data type along with the collection.


#dtype parameter 

dt = np.array([10, 20, 30], dtype = complex) 

print("Array elements with dtype complex:-", dt)

print()

dt1 = np.array([10, 20, 30], dtype = float) 

print("Array elements with dtype float:-", dt1)

print()

dt2 = np.array([15.6, 25.5, 35.8], dtype = int) 

print("Array elements with dtype int:-", dt2)

Array elements with dtype complex:- [10.+0.j 20.+0.j 30.+0.j]

Array elements with dtype float:- [10. 20. 30.]

Array elements with dtype int:- [15 25 35]


### 5. Get The Data Type of Each Array Item

In [49]:
# To check the data type of each array item, the dtype function is used. 

# Consider the following example to check the data type of the array items.

# Finding the data type of each array item

x = np.array([10,20,30])  

print("Each item is of the type :-", x.dtype)

print()

x1 = np.array([10.5,20.6,30.7])  

print("Each item is of the type :-", x1.dtype)

print()

x2 = np.array([10+5j,20.6+3j,30.7+4j])  

print("Each item is of the type :-", x2.dtype)

Each item is of the type :- int32

Each item is of the type :- float64

Each item is of the type :- complex128


### 6. Get The Dimensions of Array

In [39]:
# The ndim paramater of the array should use to find the dimensions of the array.

# Get dimension of the array

dim = np.array([[1, 2, 3, 4], [7, 8, 6, 7], [9, 10, 11, 12]]) 

print("Dimension of the given array :- ",dim.ndim) 
print()
print("Array Elements:-\n\n ",dim)

Dimension of the given array :-  2

Array Elements:-

  [[ 1  2  3  4]
 [ 7  8  6  7]
 [ 9 10 11 12]]


### 7. Get The Size of Each Array Element

In [44]:
# The itemsize function is used to get the size of each array item.

# It returns the number of bytes taken by each array element.

# Finding the size of each item in the array  

sz = np.array([10,20,30])

print("Size of each item in bytes :",sz.itemsize)  

print()

sz1 = np.array([[10,20,30],[15,25,45]])

print("Size of each item in bytes :",sz1.itemsize)  

Size of each item in bytes : 4

Size of each item in bytes : 4


### 8. Shape and Size of the array

In [51]:
# To get the shape of the array and size of the array, 

# the size and shape() function associated with the NumPy array is used.

# Get shape and size of array

s = np.array([[10,20,30,40],[60,70,80,90]]) 

print("Array Size:", s.size) 

print()

print("Shape:", s.shape)

Array Size: 8

Shape: (2, 4)


### 9. NumPy Array Creation - Empty, Zeroes and Ones

In [ ]:
In Numpy, a new ndarray object can be constructed by the following given array creation routines or
using a low-level ndarray constructor.

1. numpy.empty

2. numpy.zeroes

3. numpy.ones

###### Empty Array - Using numpy.empty

This is used to create an uninitialized array of specified shape and dtype.

The syntax to use this constructor is as follows:

**numpy.empty(shape, dtype, order)**

Following is a description of parameters by this constructor:

shape: This parameter is used to indicate the desired shape of the specified array.

dtype: This parameter indicates the data type of the array items. The default value of this parameter is float.

order: The default order or value of this option is the c-style row-major order.
       This parameter can be set to F for FORTRAN-style (column-major order)

In [ ]:
# Using numpy.empty Basic Example:
    
# The following code is used to create an empty array.
# Also, elements in an array will show random values because they are not initialized:

import numpy as np 

# an array with 4 rows and 3 columns

em = np.empty([4,3], dtype = int) 

print("Creating an empty array:- \n\n", em)

print()

import numpy as np  

em1 = np.empty((3,2), dtype = int) 

print("Creating an empty array:-\n\n", em1)

**Note:-** 
    
1. C - Contiguous order

2. F - Fortran-contiguous order

3. The difference between C and F is just whether the array is row major or column major

4. C order means that operating row-rise on the array will be slightly quicker.

5. F order means that column-wise operations will be faster.

6. Specifying 'A' means that the created array is not required to have either order -
   it is allowed to be discontiguous in memory.

###### Zero Value Array - Using numpy.zeroes

This is used to return a new array of the specified size and 
each array item will be initialized with 0.

This routine is used to create the numpy array with the specified shape 
where each numpy array item is initialized to 0.

The syntax to use this constructor is as follows:

**numpy.zeros(shape, dtype, order)**  

Following is a description of parameters by this constructor:

shape: This parameter is used to indicate the desired shape of the specified array.

dtype: This parameter indicates the data type of the array items. The default value of this parameter is float.

order: The default order or value of this option is the c-style row-major order. 
       This parameter can be set to F for FORTRAN-style (column-major order).

In [73]:
# Using numpy.zeroes
    
# The below code example will create an array of dimension 3x3 with all elements initialized as 0.

import numpy as np  

zr = np.zeros((3,3), dtype = int)  

print("Array creation with zeroes:-\n\n", arr)  

print()

import numpy as np  

zr1 = np.zeros((3,2), dtype = int)  

print("Array creation with zeroes:-\n\n", zr1)  

Array creation with zeroes:-

 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Array creation with zeroes:-

 [[0 0]
 [0 0]
 [0 0]]


###### One Value Array - Using numpy.ones

This is used to return a new array of the specified size and each array item will be initialized as 1.

The syntax to use this constructor is as follows:

**numpy.ones(shape, dtype, order)**  

Following is a description of parameters by this constructor:

shape: This parameter is used to indicate the desired shape of the specified array.

dtype: This parameter indicates the data type of the array items. The default value of this parameter is float.

order: The default order or value of this option is the c-style row-major order.
       This parameter can be set to F for FORTRAN-style (column-major order)

In [79]:
# Using numpy.ones
    
import numpy as np  

n1 = np.ones((3,3), dtype = int) 

print("Array creation with one's:-\n\n", n1)  

print()

import numpy as np  

n2 = np.ones((3,2), dtype = int) 

print("Array creation with one's:-\n\n", n2)  

print()

import numpy as np  

n3 = np.ones((3,2), dtype = float) 

print("Array creation with one's:-\n\n", n3)  

print()

import numpy as np  

n4 = np.ones((3,3), dtype = complex) 

print("Array creation with one's:-\n\n", n4)  

Array creation with one's:-

 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Array creation with one's:-

 [[1 1]
 [1 1]
 [1 1]]

Array creation with one's:-

 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Array creation with one's:-

 [[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


### 10. NumPy Array Creation using existing data

**Using numpy.asarray**

The routine numpy.asarray is used for converting the Python sequence into ndarray. 

The numpy.asarray is somehow similar to numpy.array but it has fewer parameters than numpy.array. 

This function is mainly used to create an array by using the existing data 
that is in the form of lists, or tuples.

Given below is the required syntax that is used for numpy.asarray:

**numpy.asarray(sequence,  dtype, order)** 

Parameters:

sequence: This parameter is used to indicate the python sequence that is to be converted into the python array.

dtype: This parameter is used to indicate the data type of each item of the array.

order: This parameter can be either set to C or F. The default value of this parameter is C.

In [98]:
# Array using Tuple

# In the example given below we will create an array using a tuple:

import numpy as np  

# python tuple

l = (34,7,8,78)

# creating array using the tuple

t1 = np.asarray(l)

print("Creating an array using tuple elements:-", t1)  

print()

print("Type of the array elements:-", type(t1)) 

print()

# Creating array using List.

# python list

L1 = [1,2,3] 

print("List elements:-", L1)

print()

# creating array from list 

a1 = np.asarray(L1)

print("Creating an array using List elements:-", a1) 

print()

print("Type of the array elements:- ", type(a1)) 

Creating an array using tuple elements:- [34  7  8 78]

Type of the array elements:- <class 'numpy.ndarray'>

List elements:- [1, 2, 3]

Creating an array using List elements:- [1 2 3]

Type of the array elements:-  <class 'numpy.ndarray'>


## 11. NumPy Array Creation from Numerical Ranges

In [ ]:
Here, we will learn how the NumPy arrays can be created using some given specified numerical ranges.

The Numpy library provides some functions to create an array from the given specified range. 

These functions are as follows:

1. numpy.arange

2. numpy.linspace

3. numpy.logspace

###### numpy.arange

**Using numpy.arange**

This function is used to create an array by using the evenly spaced values over any given interval.

The syntax to use this function is as follows:

**numpy.arrange(start, stop, step, dtype)**

Parameters:

The parameters of the above-mentioned function are as follows:

start: This parameter mainly indicates the starting of an interval. The default value of this parameter is 0.

stop: This parameter is used to represents the value at which the interval ends excluding this value.

step: This parameter represents the number by which the interval values change.

dtype: This parameter indicates the data type of the numpy array items.

In [113]:
# Example 1:- 
    
import numpy as np 

x = np.arange(15) 

print("Array elements using arange:-", x)

print()

# Example 2:- 

import numpy as np

ar= np.arange(2,7)

print("Arange with Values:- ", ar)

print()

# The above script will return a NumPy array of size 5 with the elements 2, 3, 4, 5, and 6.

# Remember that the arange method returns an array that starts with the starting index and 
# ends at one index less than the end index.

# Example 3:- 

a=np.arange(1,10)

print("Arange 1 to 10 values:- ",a) # 10 is exclusive. so it is not included.

print()

# Example 4:- 

b=np.arange(6.0) # As we didnt specified starting point, it takes from 0

print("printing the float values: -", b)

Array elements using arange:- [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Arange with Values:-  [2 3 4 5 6]

Arange 1 to 10 values:-  [1 2 3 4 5 6 7 8 9]

printing the float values: - [0. 1. 2. 3. 4. 5.]


In [122]:
# Step is the spacing between the values. 

# Example 1:- 

ar= np.arange(2,7,2)

print("Arange with Step Value:- ", ar)

print()

# Example 2:- 

c=np.arange(1,100,5)

print("Result for step values 5:- ", c)

print()

# Example 3:- 

# Create a Sequence of Integers using arange()

# Create a sequence of integers from 0 to 20 with steps of 3

ar= np.arange(0, 20, 3)

print ("A sequential array with steps of 3:\n\n", ar)

Arange with Step Value:-  [2 4 6]

Result for step values 5:-  [ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]

A sequential array with steps of 3:

 [ 0  3  6  9 12 15 18]


In [120]:
# using this function where we will create an array with virtual numbers.

# Example 1:- 

import numpy as np  

d=np.arange(20,dtype="int")
print("Arange with Data Type int:- ", d)

print()

d1=np.arange(10,dtype='float')
print("Arange with Data Type float:- ", d1)

print()

d2=np.arange(10,dtype='complex')
print("Arange with Data Type complex:- ", d2)

print()

y = np.arange(0,10,2,complex)  

print("Array elements using arange:-", y)

Arange with Data Type int:-  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Arange with Data Type float:-  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

Arange with Data Type complex:-  [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]

Array elements using arange:- [0.+0.j 2.+0.j 4.+0.j 6.+0.j 8.+0.j]


###### NumPy.linspace

1. It is similar to the arrange function. However, it doesn't allow us to specify the step size in the syntax.

2. Instead of that, it only returns evenly separated values over a specified period. 

3. The system implicitly calculates the step size.

4. The syntax is given below.

    **numpy.linspace(start, stop, num, endpoint, retstep, dtype)**
    <br>

5. It accepts the following parameters:-

   - start: It represents the starting value of the interval.
    
   - stop: It represents the stopping value of the interval.
    
   - num: The amount of evenly spaced samples over the interval to be generated. The default is 50.
    
   - endpoint: Its true value indicates that the stopping value is included in the interval.
    
   - rettstep: This has to be a boolean value. Represents the steps and samples between the consecutive numbers.
    
   - dtype: It represents the data type of the array items.

In [123]:
# Example 1:
    
# Here, using this function, we will get an array with numbers between 20 and 30,
# and we will have evenly spaced 5 numbers from this range, hence, 20, 22.5, 25, 27.5 and 30 are picked.

import numpy as np  

# start=20, end=30, num=5

arr = np.linspace(20, 30, 5) 

print("The array in this range with linespace is ",arr)  

The array in this range with linespace is  [20.  22.5 25.  27.5 30. ]


In [125]:
# Example 2:

# For instance, if the first index is 1, the last index is 10 and 
# we need 10 equally spaced elements within this range, we can use the linspace method as follows:

import numpy as np  

lin = np.linspace(1, 10, 10)

print("NumPy Array with Linspace 10:-",lin)

print()

lin = np.linspace(1, 10, 20)

print("NumPy Array with Linspace 20:-\n \n",lin)

# Notice that the output might look like a matrix, but actually it is a one-dimensional array.

# Because of the spacing issue, the elements have been displayed in multiple lines.

NumPy Array with Linspace 10:- [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

NumPy Array with Linspace 20:-
 
 [ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [126]:
# Example 3:

c = np.linspace(1, 100, num=5)
print("Output evenly spaced values:-", c)  # Here it will display 5 numbers that are evenly spaced between 1 to 100

print()

c1 = np.linspace(1, 100, num=10, endpoint=True)
print("Output evenly spaced values with endpoint:-", c1)  # Endpoint is false, it will exclude 100.

print()

c2 = np.linspace(1, 100, num=5, retstep=True)
print("Output evenly spaced step value between array elements:-", c2)  # Returns the step value

print()

c3 = np.linspace(1, 100, num=5, dtype=int)
print("Output evenly spaced values with datatype:-",c3)

print()

c4 = np.linspace(1,10)
print("Output 50 values as default value of Num is 50:-\n \n",c4)

Output evenly spaced values:- [  1.    25.75  50.5   75.25 100.  ]

Output evenly spaced values with endpoint:- [  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]

Output evenly spaced step value between array elements:- (array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ]), 24.75)

Output evenly spaced values with datatype:- [  1  25  50  75 100]

Output 50 values as default value of Num is 50:-
 
 [ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.  

###### numpy.logspace

1. It creates an array by using the numbers that are evenly separated on a log scale.

2. The syntax is given below.
  
    **numpy.logspace(start, stop, num, endpoint, base, dtype)**  
    <br>

3. It accepts the following parameters.

   - start: It represents the starting value of the interval in the base.
   - stop: It represents the stopping value of the interval in the base.
   - num: The number of values between the range.
   - endpoint: It is a boolean type value. It makes the value represented by stop as the last value of the interval.
   - base: It represents the base of the log space.
   - dtype: It represents the data type of the array items.

In [133]:
# Example:-
    
import numpy as np  

a = np.logspace(20, 30, num = 4, endpoint = True)

print("NumPy array with Logspace:-\n\n",a) 

print()

import numpy as np  

arr = np.logspace(5, 30, num = 4,base = 3, endpoint = True)

print("NumPy array with Logspace:- \n\n",arr)  

NumPy array with Logspace:-

 [1.00000000e+20 2.15443469e+23 4.64158883e+26 1.00000000e+30]

NumPy array with Logspace:- 

 [2.43000000e+02 2.29941166e+06 2.17584115e+10 2.05891132e+14]


## 12. Convert NumPy Array to Python List - tolist()

In [ ]:
We can convert the Numpy array to the list by using tolist() method.

We may have a list of data elements that have been converted from the array using this method.

# Syntax of tolist()

ndarray.tolist()

Parameters: none
    
Returns: The possibly nested list of array elements.

Before going to convert from NumPy array to Python list we have to import the required module,
after that, we have to create an array and then use the tolist() method to convert array to list.
After using this method we have to check the type of class using the type() method.

###### Convert One Dimensional Array To List

In [135]:
# Example:-

# create array

array = np.array([10, 20, 30, 40])

print("Array:", array)

print(type(array))

print()

# Convert list

list = array.tolist()

print("list:", list)

print(type(list))

Array: [10 20 30 40]
<class 'numpy.ndarray'>

list: [10, 20, 30, 40]
<class 'list'>


In [ ]:
Convert Multi Dimensional Array to list

In [141]:
# Example:-

# create array

array = np.array([[10, 20, 30, 40],
                  [50, 60, 70, 80],
                  [60, 40 ,20 ,10]])  

print("Array:- \n\n", array)

print()

print(type(array))

print()
  
# Convert list

list = array.tolist()

print("List:- \n\n", list)

print()

print(type(array))

Array:- 

 [[10 20 30 40]
 [50 60 70 80]
 [60 40 20 10]]

<class 'numpy.ndarray'>

List:- 

 [[10, 20, 30, 40], [50, 60, 70, 80], [60, 40, 20, 10]]

<class 'numpy.ndarray'>
