In [ ]:
1. Import numpy as np and get the version?

In [5]:
import numpy as np
print('Latest Version of NumPy:- ',np.__version__)

Latest Version of NumPy:-  1.19.2


In [ ]:
2. Create a 1D array of numbers from 0 to 49?

In [3]:
import numpy as np
x=np.arange(50)
print('1D array of numbers from 0 to 49:- \n',x)

1D array of numbers from 0 to 49:- 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [ ]:
3. Create an empty array of 10 0's and replace the 4th object with the number 5?

In [94]:
import numpy as np
x1=np.zeros(10)
print('Print 10 Zeros:- \n',x1)
x1[3]=5
print('Replacing the 4th element with the number 5:- \n',x1)

Print 10 Zeros:- 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Replacing the 4th element with the number 5:- 
 [0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]


In [95]:
4. Create a 1D array of numbers from 0 to 19?
   
    - Extract all odd numbers from the array? 
    
    - Replace all odd numbers in array with -1?

In [99]:
import numpy as np
x4 = np.arange(0,20)
print('1D array of numbers from 0 to 19, x4 :- \n',x4)
print()
x5=np.arange(1,20,2)
print('Odd Numbers between 0 and 19, x5 :- \n',x5)
print()
x5[:]=-1 
print('Replace all odd numbers in array with -1 in x5:- \n',x5)
print()

1D array of numbers from 0 to 19, x4 :- 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Odd Numbers between 0 and 19, x5 :- 
 [ 1  3  5  7  9 11 13 15 17 19]

Replace all odd numbers in array with -1 in x5:- 
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


In [57]:
 5. Create an array of ten 1's and store it as a variable named 'a_master'. 
    Copy the same array into another variable named 'a_copy'?

In [56]:
import numpy as np

a_master= np.ones(10)
print('Ten ones and store in a variable named a_master:- \n', a_master)
print()
a_copy =np.copy(a_master)
print('Copying the same array into another variable named:- a_copy \n', a_copy)

Ten ones and store in a variable named a_master:- 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Copying the same array into another variable named:- a_copy 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
6. Create an array containing fifty 1's and broadcast/change all the one's to the value 100?

In [100]:
import numpy as np
x7=np.ones(50)
print(x7)
x7[:]=100
print(x7)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]
[100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 100. 100. 100. 100. 100. 100.]


In [ ]:
7. Create an array of integers starting from 21 until 31 and name it as array1

   Create an array of integers starting from 11 until 21 and name it array2

   Calculate the difference between array1 and array2?

In [73]:
import numpy as np
array1=np.arange(21,32)
print('An array of integers starting from 21 until 31 and named it as array1 :- \n',array1)
print()
array2=np.arange(11,22)
print('An array of integers starting from 11 until 21 and named it as array2 :- \n',array2)
print()
x7=array1-array2
print('The difference between array1 and array2 :- \n',x7)

An array of integers starting from 21 until 31 and named it as array1 :- 
 [21 22 23 24 25 26 27 28 29 30 31]

An array of integers starting from 11 until 21 and named it as array2 :- 
 [11 12 13 14 15 16 17 18 19 20 21]

The difference between array1 and array2 :- 
 [10 10 10 10 10 10 10 10 10 10 10]


In [ ]:
8. Create a 3×3 numpy array of all True’s ? 

   HINT:- np.full((n, n), True, dtype=bool)  or np.ones((n,n), dtype=bool)

In [92]:
x8=np.ones((3,3),dtype=bool)
print(x8)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [88]:
x8=np.full((3, 3), True, dtype=bool)
print(x8)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
9. Create an array of all even integers from 2 to 10 with arange() method and name it a1

   Create an array of all even integers from 22 to 30 with arange() method and name it a2

   a) Use the 2 arrays as rows and create a matrix [ Hint - Use stack function from numpy ]

   b) Use the 2 arrays as columns and create a matrix [ Hint - Use column_stack function from numpy ]

In [110]:
a1=np.arange(2,11,2)
print('an array of all even integers from 2 to 10:- \n',a1)
a2=np.arange(22,31,2)
print('an array of all even integers from 22 to 30:- \n',a2)
x6=np.row_stack((a1,a2))
print('Use the 2 arrays as rows and create a matrix :- \n',x6)
x7=np.column_stack((a1,a2))
print('Use the 2 arrays as columns and create a matrix :- \n',x7)

an array of all even integers from 2 to 10:- 
 [ 2  4  6  8 10]
an array of all even integers from 22 to 30:- 
 [22 24 26 28 30]
Use the 2 arrays as rows and create a matrix :- 
 [[ 2  4  6  8 10]
 [22 24 26 28 30]]
Use the 2 arrays as columns and create a matrix :- 
 [[ 2 22]
 [ 4 24]
 [ 6 26]
 [ 8 28]
 [10 30]]


In [ ]:
10. Convert a 1D array to a 2D array with 2 rows using reshape() method? 

In [112]:
x8=np.arange(1,7)
print(x8)
x9=x8.reshape(2,3)
print(x9)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
11. Create a 5x6 matrix with values ranging from 0 to 49 with arange() & reshape() methods 
    and retrieve the value intersecting at 2nd row and 3rd column? 

In [121]:
n1=np.arange(1,31)
print(n1)
n2=n1.reshape(5,6)
print(n2)
n3=n2[1:2,2:3]
print(n3)
print(n1[1:3])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
[[9]]
[2 3]


In [ ]:
12. Create an identity matrix of shape 10x10 and replace the 0's with the value 50.

In [193]:
#n4=np.eye(10)
n4=np.identity(10)
#print("Identity Matrix:- \n", n4)
print()

n5=np.where(n4==0)
for i in n5:
    n4[n5]=np.random.randint(50,51)
print(n4)


[[ 1. 50. 50. 50. 50. 50. 50. 50. 50. 50.]
 [50.  1. 50. 50. 50. 50. 50. 50. 50. 50.]
 [50. 50.  1. 50. 50. 50. 50. 50. 50. 50.]
 [50. 50. 50.  1. 50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50.  1. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50.  1. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.  1. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50. 50.  1. 50. 50.]
 [50. 50. 50. 50. 50. 50. 50. 50.  1. 50.]
 [50. 50. 50. 50. 50. 50. 50. 50. 50.  1.]]


In [1]:
import numpy as np

n4=np.eye(10)
print("Identity Matrix:- \n", n4)
print()

n4[:1,1:]=50
#print(n4)
print()
n4[1:,:1]=50
#print(n4)
print()
n4[1:,:1]=50
#print(n4)
print()
n4[2:,1:2]=50
#print(n4)
print()
n4[1:2,2:]=50
#print(n4)
print()
n4[3:,2:3]=50
#print(n4)
print()
n4[2:3,3:]=50
#print(n4)
print()
n4[4:,3:4]=50
print(n4)

Identity Matrix:- 
 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]








[[ 1. 50. 50. 50. 50. 50. 50. 50. 50. 50.]
 [50.  1. 50. 50. 50. 50. 50. 50. 50. 50.]
 [50. 50.  1. 50. 50. 50. 50. 50. 50. 50.]
 [50. 50. 50.  1.  0.  0.  0.  0.  0.  0.]
 [50. 50. 50. 50.  1.  0.  0.  0.  0.  0.]
 [50. 50. 50. 50.  0.  1.  0.  0.  0.  0.]
 [50. 50. 50. 50.  0.  0.  1.  0.  0.  0.]
 [50. 50. 50. 50.  0.  0.  0.  1.  0.  0.]
 [50. 50. 50. 50.  0.  0.  0.  0.  1.  0.]
 [50. 50. 50. 50.  0.  0.  0.  0.  0.  1.]]


In [ ]:
13. Get the common items between two python numpy arrays?

     a = np.array([1,2,3,2,3,4,3,4,5,6])
     b = np.array([7,2,10,2,7,4,9,4,9,8])
        
     Desired Output: array([2, 4])
    
     HINT : intersect1d()

In [154]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print('the common items between two python numpy arrays:- \n',np.intersect1d(a,b))

the common items between two python numpy arrays:- 
 [2 4]


In [ ]:
14. How to reverse the rows of a 2D array?

    x = np.arange(9).reshape(3,3)

In [198]:
import numpy as np
x=np.arange(9)
print(x)
y =x[::-1]
print('Reverse of x:-\n',y)
print()
k=np.flip(x)
print('Flip of x:-\n',k)
print()

z= x.reshape(3,3)
print('Matrix:-Z \n',z)
print()

M=z[::-1]
print('Reverse of z:-\n',M)
print()
N=np.flip(z)
print('Flip of z:-\n',N)

[0 1 2 3 4 5 6 7 8]
Reverse of x:-
 [8 7 6 5 4 3 2 1 0]

Flip of x:-
 [8 7 6 5 4 3 2 1 0]

Matrix:-Z 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Reverse of z:-
 [[6 7 8]
 [3 4 5]
 [0 1 2]]

Flip of z:-
 [[8 7 6]
 [5 4 3]
 [2 1 0]]


In [175]:
import numpy as np
arr = np.array([6, 1, 4, 2, 18, 9, 3, 4, 2, 8, 11])
reversedArr = np.flip(arr)
print('Reversed Array : ', reversedArr)

Reversed Array :  [11  8  2  4  3  9 18  2  4  1  6]


In [ ]:
`15. How to reverse the columns of a 2D array?

     x = np.arange(9).reshape(3,3)

In [199]:
import numpy as np
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
16. Use NumPy to generate a random set of 10 numbers between 0 and 1?

    Display a boolean array output where all values > 0.2 are True, rest are marked as False?

In [236]:
import numpy as np    
r1=np.random.normal(0,1,10)
print(r1)

for i in r1:
    r2=i>0.2
    print(r2)

[-0.42873014  0.96410167 -1.81428131 -1.35138591  0.20927387  1.33841884
 -0.47755088  0.34894414 -0.60796529 -0.42843043]
False
True
False
False
True
True
False
True
False
False


In [ ]:
17. Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution

In [230]:
import numpy as np
random = np.random.randn(5, 2)

print("Matrix with randn() function:-\n \n ",random)

Matrix with randn() function:-
 
  [[-0.29348888  0.73888736]
 [-0.13835665 -0.5634486 ]
 [ 1.5476944  -1.19563326]
 [ 0.87171708  1.12860507]
 [ 1.72978341  0.19577412]]


In [ ]:
18. Create an array of 30 linearly spaced points between 0 and 100: ?

In [238]:
import numpy as np
x1 = np.linspace(0, 100, 30)
print('Array of 30 linearly spaced points between 0 and 100:- \n',x1)

Array of 30 linearly spaced points between 0 and 100:- 
 [  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
  86.20689655  89.65517241  93.10344828  96.55172414 100.        ]


###### Ignore 19 question

In [240]:
19. How to drop all missing values from a numpy array?

    Input: np.array([1,2,3,np.nan,5,6,7,np.nan])

    Desired Output: array([ 1.,  2.,  3.,  5.,  6.,  7.])

In [246]:
import numpy as np

y1= np.array([1,2,3,np.nan,5,6,7,np.nan])
print('y1:- ',y1)

y2= np.array([True,True,True,False,True,True,True,False])
print('y2:- ',y2)

y3=y1[y2]
print('y3:- ',y3)

y1:-  [ 1.  2.  3. nan  5.  6.  7. nan]
y2:-  [ True  True  True False  True  True  True False]
y3:-  [1. 2. 3. 5. 6. 7.]


###### Numpy Indexing and Selections

In [ ]:
20. Using the below given Matrix, generate the output for the below questions:-

In [253]:
# 1. Retrieve the last 2 rows and first 3 column values of the above matrix:

import numpy as np
a = np.arange(1,101).reshape(10,10)
print(a)
print()
print('a:Retrieve the last 2 rows and first 3 column values of the above matrix:- \n',a[8:,:3])

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

a:Retrieve the last 2 rows and first 3 column values of the above matrix:- 
 [[81 82 83]
 [91 92 93]]


In [303]:
print('Shape of matrix:- \n',a.shape[0])
print('Identify the rows :- \n',a.reshape(5,-1))

Shape of matrix:- 
 10
Identify the rows :- 
 [[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20]
 [ 21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38
   39  40]
 [ 41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
   59  60]
 [ 61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
   79  80]
 [ 81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98
   99 100]]


In [302]:
# b) Retrieve the value 55 from the above matrix using index & selection technique?

print ('b) Retrieve the value 55 from the above matrix :- \n',a[5:6,4:5])


b) Retrieve the value 55 from the above matrix :- 
 [[55]]


In [256]:
# c) Retrieve the values from the 3rd column in the above matrix?

print('c) Retrieve the values from the 3rd column :- \n',a[:,2:3])


c) Retrieve the values from the 3rd column :- 
 [[ 3]
 [13]
 [23]
 [33]
 [43]
 [53]
 [63]
 [73]
 [83]
 [93]]


In [257]:
# d) Retrieve the values from the 4th row in the above matrix?

print('d) Retrieve the values from the 4th row :- \n',a[3:4,:])

d) Retrieve the values from the 4th row :- 
 [[31 32 33 34 35 36 37 38 39 40]]


In [263]:
# e) Retrieve values from the 2nd & 4th rows in the above matrix?

print('e) Retrieve values from the 2nd & 4th rows :- \n',a[1:2,:])

print('e) Retrieve values from the 2nd & 4th rows :- \n',a[3:4,:])

e) Retrieve values from the 2nd & 4th rows :- 
 [[11 12 13 14 15 16 17 18 19 20]]
e) Retrieve values from the 2nd & 4th rows :- 
 [[31 32 33 34 35 36 37 38 39 40]]


In [306]:
#f) Calculate sum of all the values in the matrix?

print('f) Calculate sum of all the values in the matrix:- \n',a.sum())
print('f) Calculate sum of all the Row values in the matrix:- \n',a.sum(axis=1))
print('f) Calculate sum of all the Column values in the matrix:- \n',a.sum(axis=0))

f) Calculate sum of all the values in the matrix:- 
 5050
f) Calculate sum of all the Row values in the matrix:- 
 [ 55 155 255 355 455 555 655 755 855 955]
f) Calculate sum of all the Column values in the matrix:- 
 [460 470 480 490 500 510 520 530 540 550]


In [270]:
# g) Calculate standard deviation of all the values in the matrix?

print('g) Calculate standard deviation of all the values:- \n',np.std(a))

g) Calculate standard deviation of all the values:- 
 28.86607004772212


In [ ]:
# h) Calculate the variance of all values in the matrix?

print('h) Calculate the variance of all values:- \n',)

In [271]:
# i) Calculate the mean of all values in the matrix?

print('i) Calculate the mean of all values :- \n',np.mean(a))

i) Calculate the mean of all values :- 
 50.5


In [269]:
# j) Retrieve the largest number from the matrix.

print('j) Retrieve the largest number from the matrix :- \n',a.max())

j) Retrieve the largest number from the matrix :- 
 100


In [268]:
# k) Retrieve the smallest number from the matrix.

print('k) Retrieve the smallest number from the matrix :- \n',a.min())

k) Retrieve the smallest number from the matrix :- 
 1


In [ ]:
a) Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique>

b) Retrieve the value 55 from the above matrix using index & selection technique?

c) Retrieve the values from the 3rd column in the above matrix?

d) Retrieve the values from the 4th row in the above matrix?

e) Retrieve values from the 2nd & 4th rows in the above matrix?

f) Calculate sum of all the values in the matrix?

g) Calculate standard deviation of all the values in the matrix?

h) Calculate the variance of all values in the matrix?

i) Calculate the mean of all values in the matrix?

j) Retrieve the largest number from the matrix

k) Retrieve the smallest number from the matrix